Blog app - views
TamaraDimov/Blog-app pull request #6
Opened 2023-08-24 12:54 UTC by TamaraDimov

Requirements:

- [ ]  Implement the design from the sneak peek wireframes
- [ ]  I create an HTML view for user and post.
- [ ]  I create comment HTML file.

2023-08-24 13:32 UTC, MahmoudBakr23 requested changes
Hello @TamaraDimov 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Well done working with the controllers so far
- Nice job using partials in the views
- Descriptive PR and README
- Correct Linters

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️

- [ ] Kindly fully follow the given design wireframe and implement the styles in your app. 🙏 

_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers, and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 13:32 UTC, MahmoudBakr23 commented on app/views/posts/_post.html.erb
> +      </div>
- [ ] Please make sure that the content rendered in the `posts/index` is the posts with the most recent 3 comments for each. 🙏

2023-08-24 13:32 UTC, MahmoudBakr23 commented on app/views/posts/_post.html.erb
> +        </ddiv>
- [ ] Please fix the typo here in the `div` tag on line 8 🙏

2023-08-24 23:45 UTC, Owusu-Desmond requested changes
Hi @TamaraDimov , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

Your project have an error while setting up, this error happens when creating comments in your seed.rb so make sure you fix this :pray: 

![image](https://github.com/TamaraDimov/Blog-app/assets/92303891/d563687b-485b-4dbe-bb80-f53dfc68b122)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-25 05:23 UTC, Ibizugbe approved these changes
Hi @TamaraDimov 👋🏼👋🏼👋🏼, 

![approved](https://github.com/TamaraDimov/Blog-app/assets/64643995/034e2dd3-55db-4f19-a583-d3aa0273f612)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Typo error has been fixed on `_post.html.erb` as requested by the previous reviewer👍🏼.
- [x] The post/index now renders the 3 most recent posts👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 05:33 UTC, merged